const chalk = require('chalk');

module.exports = function (program) {
  program.command('schedule').action(function () {
    console.log(chalk.cyan(".==============================."));
    console.log(chalk.cyan("|           SCHEDULE           |"));
    console.log(chalk.cyan("'=============================='"));
    console.log("");
    console.log(chalk.yellow("July 26"));
    console.log(chalk.yellow("-------"));
    console.log(" 8:00 PM Informal pre-party, downtown LOCAL");
    console.log("");
    console.log(chalk.yellow("July 27"));
    console.log(chalk.yellow("-------"));
    console.log(" 8:00 AM  REGISTRATION");
    console.log("          Doors Open, Registration starts");
    console.log("");
    console.log(" 9:00 AM  WELCOME");
    console.log("          Introductions / Kick-off");
    console.log("");
    console.log(" 9:15 AM  LAURIE VOSS");
    console.log("          Keynote: npm and the Future of JavaScript");
    console.log("");
    console.log("10:00 AM  CARMEN BOURLON");
    console.log("          At Your Service with Service Workers");
    console.log("");
    console.log("10:30 AM  BREAK");
    console.log("");
    console.log("11:00 AM  KARL GROVES");
    console.log("          What Is This Thing and What Does It Do?");
    console.log("");
    console.log("11:30 AM  MICHAEL CHAN");
    console.log("          Hot Garbage: Clean Code is Dead");
    console.log("");
    console.log("12:00 PM  LUNCH");
    console.log("          Taco/Fajita Bar!");
    console.log("");
    console.log(" 1:30 PM  BEN ILEGBODU");
    console.log("          Let’s Web Dev Like It’s 1999!");
    console.log("");
    console.log(" 2:00 PM  ANDREY SITNIK");
    console.log("          CRDT: Conflict-free Data Types for Collaborative Editing and Offline-First");
    console.log("");
    console.log(" 2:30 PM  BETH HAUBERT");
    console.log("          WTF Are Serverless Apps? ¯\_(ツ)_/¯");
    console.log("");
    console.log(" 3:00 PM  BREAK");
    console.log("");
    console.log(" 3:30 PM  STEVE KINNEY");
    console.log("          Actually Understanding Asynchronous JavaScript");
    console.log("");
    console.log(" 4:00 PM  CLARISSA PETERSON");
    console.log("          Keynote—Code is Not Neutral: The Ethics of Web Development");
    console.log("");
    console.log(" 4:45 PM  CLOSING");
    console.log("          Closing Remarks and Post-Conference Happy Hour");
  });
};
